export const fontSizeBody1: string
export const fontSizeBody2: string
export const fontSizeBody3: string
export const fontSizeBody4: string
export const fontSizeButton: string
export const fontSizeCaption: string
export const fontSizeDAppBody1: string
export const fontSizeDAppBody3: string
export const fontSizeDAppBody4: string
export const fontSizeDAppButton: string
export const fontSizeDAppDayshours: string
export const fontSizeDAppHeadline1: string
export const fontSizeDAppHeadline2: string
export const fontSizeDAppNumber: string
export const fontSizeDAppTitle1: string
export const fontSizeDAppTitle2: string
export const fontSizeDAppTitle3: string
export const fontSizeDAppTitle4: string
export const fontSizeDAppTitle5: string
export const fontSizeH1: string
export const fontSizeH2: string
export const fontSizeH3: string
export const fontSizeH4: string
export const fontSizeH5: string
export const fontSizeH6: string
export const fontSizeOverline: string
export const fontSizeSubtitle1: string
export const fontSizeSubtitle2: string
export const fontSizeTitle1: string
export const fontSizeTitle2: string
export const fontSizeTitle3: string
export const fontSizeTitle4: string
export const fontSizeTitle5: string
export const fontTheBadgeWeb: string
export const fontWeightBlack: string
export const fontWeightBold: string
export const fontWeightExtraBold: string
export const fontWeightExtraLarge: string
export const fontWeightLarge: string
export const fontWeightNormal: string
export const fontWeightThin: string
export const lineHeightBody1: string
export const lineHeightBody2: string
export const lineHeightBody3: string
export const lineHeightBody4: string
export const lineHeightButton: string
export const lineHeightCaption: string
export const lineHeightDAppBody1: string
export const lineHeightDAppBody3: string
export const lineHeightDAppBody4: string
export const lineHeightDAppButton: string
export const lineHeightDAppDayshours: string
export const lineHeightDAppHeadline1: string
export const lineHeightDAppHeadline2: string
export const lineHeightDAppNumber: string
export const lineHeightDAppTitle1: string
export const lineHeightDAppTitle2: string
export const lineHeightDAppTitle3: string
export const lineHeightDAppTitle4: string
export const lineHeightDAppTitle5: string
export const lineHeightH1: string
export const lineHeightH2: string
export const lineHeightH3: string
export const lineHeightH4: string
export const lineHeightH5: string
export const lineHeightH6: string
export const lineHeightOverline: string
export const lineHeightSubtitle1: string
export const lineHeightSubtitle2: string
export const lineHeightTitle1: string
export const lineHeightTitle2: string
export const lineHeightTitle3: string
export const lineHeightTitle4: string
export const lineHeightTitle5: string
