export const black: string
export const blackBackground: string
export const blackText: string
export const blue: string
export const blueDark: string
export const blueInfo: string
export const blueLight: string
export const gradient0: string
export const gradient1: string
export const gradient2: string
export const gradient3: string
export const gradient4: string
export const green: string
export const greenBorder: string
export const greenHover: string
export const greenSuccess: string
export const greyBackground: string
export const orangeWarning: string
export const pink: string
export const pinkLight: string
export const primary: string
export const primaryDark: string
export const primaryLight: string
export const purple: string
export const redError: string
export const secondary: string
export const secondaryDark: string
export const secondaryLight: string
export const transparent: string
export const white: string
