export const black: string
export const blackBackground: string
export const blackText: string
export const blue: string
export const blueDark: string
export const blueInfo: string
export const blueLight: string
export const darkBlue: string
export const darkGreen: string
export const fontSizeBody1: string
export const fontSizeBody2: string
export const fontSizeBody3: string
export const fontSizeBody4: string
export const fontSizeButton: string
export const fontSizeCaption: string
export const fontSizeH1: string
export const fontSizeH2: string
export const fontSizeH3: string
export const fontSizeH4: string
export const fontSizeH5: string
export const fontSizeH6: string
export const fontSizeOverline: string
export const fontSizeSubtitle1: string
export const fontSizeSubtitle2: string
export const fontSizeTitle1: string
export const fontSizeTitle2: string
export const fontSizeTitle3: string
export const fontSizeTitle4: string
export const fontSizeTitle5: string
export const fontTheBadgeWeb: string
export const fontWeightBlack: string
export const fontWeightBold: string
export const fontWeightExtraBold: string
export const fontWeightExtraLarge: string
export const fontWeightLarge: string
export const fontWeightNormal: string
export const fontWeightThin: string
export const gradient0: string
export const gradient1: string
export const gradient2: string
export const gradient3: string
export const gradient4: string
export const gradient5: string
export const green: string
export const greenBorder: string
export const greenDark: string
export const greenHover: string
export const greenLight: string
export const greenSuccess: string
export const greyBackground: string
export const l: string
export const lineHeightBody1: string
export const lineHeightBody2: string
export const lineHeightBody3: string
export const lineHeightBody4: string
export const lineHeightButton: string
export const lineHeightCaption: string
export const lineHeightH1: string
export const lineHeightH2: string
export const lineHeightH3: string
export const lineHeightH4: string
export const lineHeightH5: string
export const lineHeightH6: string
export const lineHeightOverline: string
export const lineHeightSubtitle1: string
export const lineHeightSubtitle2: string
export const lineHeightTitle1: string
export const lineHeightTitle2: string
export const lineHeightTitle3: string
export const lineHeightTitle4: string
export const lineHeightTitle5: string
export const m: string
export const orangeWarning: string
export const pink: string
export const pinkDark: string
export const pinkLight: string
export const primary: string
export const primaryDark: string
export const primaryLight: string
export const purple: string
export const redError: string
export const s: string
export const secondary: string
export const secondaryDark: string
export const secondaryLight: string
export const transparent: string
export const violet: string
export const white: string
export const xl: string
export const xxl: string
