export const black: string
export const blackBackground: string
export const blackText: string
export const blue: string
export const blueDark: string
export const blueInfo: string
export const blueLight: string
export const darkBlue: string
export const darkGreen: string
export const deepPurple: string
export const fontSizeBody1: string
export const fontSizeBody2: string
export const fontSizeBody3: string
export const fontSizeBody4: string
export const fontSizeBodyLarge: string
export const fontSizeBodyMedium: string
export const fontSizeBodySmall: string
export const fontSizeButton: string
export const fontSizeCaption: string
export const fontSizeDAppBody1: string
export const fontSizeDAppBody3: string
export const fontSizeDAppBody4: string
export const fontSizeDAppButton: string
export const fontSizeDAppDayshours: string
export const fontSizeDAppHeadline1: string
export const fontSizeDAppHeadline2: string
export const fontSizeDAppNumber: string
export const fontSizeDAppTitle1: string
export const fontSizeDAppTitle2: string
export const fontSizeDAppTitle3: string
export const fontSizeDAppTitle4: string
export const fontSizeDAppTitle5: string
export const fontSizeDisplayLarge: string
export const fontSizeDisplayMedium: string
export const fontSizeDisplaySmall: string
export const fontSizeH1: string
export const fontSizeH2: string
export const fontSizeH3: string
export const fontSizeH4: string
export const fontSizeH5: string
export const fontSizeH6: string
export const fontSizeHeadlineLarge: string
export const fontSizeHeadlineMedium: string
export const fontSizeHeadlineSmall: string
export const fontSizeLabelLarge: string
export const fontSizeLabelMedium: string
export const fontSizeLabelSmall: string
export const fontSizeOverline: string
export const fontSizeSubtitle1: string
export const fontSizeSubtitle2: string
export const fontSizeTitle1: string
export const fontSizeTitle2: string
export const fontSizeTitle3: string
export const fontSizeTitle4: string
export const fontSizeTitle5: string
export const fontSizeTitleLarge: string
export const fontSizeTitleMedium: string
export const fontSizeTitleSmall: string
export const fontTheBadgeWeb: string
export const fontWeightBlack: string
export const fontWeightBodyLarge: string
export const fontWeightBodyMedium: string
export const fontWeightBodySmall: string
export const fontWeightBold: string
export const fontWeightDisplayLarge: string
export const fontWeightDisplayMedium: string
export const fontWeightDisplaySmall: string
export const fontWeightExtraBold: string
export const fontWeightExtraLarge: string
export const fontWeightHeadlineLarge: string
export const fontWeightHeadlineMedium: string
export const fontWeightHeadlineSmall: string
export const fontWeightLabelLarge: string
export const fontWeightLabelMedium: string
export const fontWeightLabelSmall: string
export const fontWeightLarge: string
export const fontWeightNormal: string
export const fontWeightThin: string
export const fontWeightTitleLarge: string
export const fontWeightTitleMedium: string
export const fontWeightTitleSmall: string
export const green: string
export const greenBorder: string
export const greenDark: string
export const greenHover: string
export const greenLight: string
export const greenLogo: string
export const greenSuccess: string
export const greyBackground: string
export const greyStroke: string
export const letterSpacingBodyLarge: string
export const letterSpacingBodyMedium: string
export const letterSpacingLabelLarge: string
export const letterSpacingLabelMedium: string
export const letterSpacingLabelSmall: string
export const letterSpacingTitleMedium: string
export const letterSpacingTitleSmall: string
export const lineHeightBody1: string
export const lineHeightBody2: string
export const lineHeightBody3: string
export const lineHeightBody4: string
export const lineHeightBodyLarge: string
export const lineHeightBodyMedium: string
export const lineHeightBodySmall: string
export const lineHeightButton: string
export const lineHeightCaption: string
export const lineHeightDAppBody1: string
export const lineHeightDAppBody3: string
export const lineHeightDAppBody4: string
export const lineHeightDAppButton: string
export const lineHeightDAppDayshours: string
export const lineHeightDAppHeadline1: string
export const lineHeightDAppHeadline2: string
export const lineHeightDAppNumber: string
export const lineHeightDAppTitle1: string
export const lineHeightDAppTitle2: string
export const lineHeightDAppTitle3: string
export const lineHeightDAppTitle4: string
export const lineHeightDAppTitle5: string
export const lineHeightDisplayLarge: string
export const lineHeightDisplayMedium: string
export const lineHeightDisplaySmall: string
export const lineHeightH1: string
export const lineHeightH2: string
export const lineHeightH3: string
export const lineHeightH4: string
export const lineHeightH5: string
export const lineHeightH6: string
export const lineHeightHeadlineLarge: string
export const lineHeightHeadlineMedium: string
export const lineHeightHeadlineSmall: string
export const lineHeightLabelLarge: string
export const lineHeightLabelMedium: string
export const lineHeightLabelSmall: string
export const lineHeightOverline: string
export const lineHeightSubtitle1: string
export const lineHeightSubtitle2: string
export const lineHeightTitle1: string
export const lineHeightTitle2: string
export const lineHeightTitle3: string
export const lineHeightTitle4: string
export const lineHeightTitle5: string
export const lineHeightTitleLarge: string
export const lineHeightTitleMedium: string
export const lineHeightTitleSmall: string
export const orangeWarning: string
export const pink: string
export const pinkDark: string
export const pinkLight: string
export const primary: string
export const primaryDark: string
export const primaryLight: string
export const purple: string
export const redError: string
export const secondary: string
export const secondaryDark: string
export const secondaryLight: string
export const srOnly: string
export const textUnderline: string
export const textUnderlineWhite: string
export const transparent: string
export const white: string
