export const backgroundColorBlack: string
export const backgroundColorBlackBackground: string
export const backgroundColorBlackText: string
export const backgroundColorBlue: string
export const backgroundColorBlueDark: string
export const backgroundColorBlueInfo: string
export const backgroundColorBlueLight: string
export const backgroundColorDarkBlue: string
export const backgroundColorDarkGreen: string
export const backgroundColorDeepPurple: string
export const backgroundColorGreen: string
export const backgroundColorGreenBorder: string
export const backgroundColorGreenDark: string
export const backgroundColorGreenHover: string
export const backgroundColorGreenLight: string
export const backgroundColorGreenSuccess: string
export const backgroundColorGreyBackground: string
export const backgroundColorInherit: string
export const backgroundColorOrangeWarning: string
export const backgroundColorPink: string
export const backgroundColorPinkDark: string
export const backgroundColorPinkLight: string
export const backgroundColorPrimary: string
export const backgroundColorPrimaryDark: string
export const backgroundColorPrimaryLight: string
export const backgroundColorPurple: string
export const backgroundColorRedError: string
export const backgroundColorSecondary: string
export const backgroundColorSecondaryDark: string
export const backgroundColorSecondaryLight: string
export const backgroundColorTransparent: string
export const backgroundColorWhite: string
export const backgroundGradient0: string
export const backgroundGradient1: string
export const backgroundGradient2: string
export const backgroundGradient3: string
export const backgroundGradient4: string
export const backgroundGradient5: string
export const backgroundGradientBackground: string
export const backgroundGradientHeader: string
export const backgroundInherit: string
export const black: string
export const blackBackground: string
export const blackText: string
export const blue: string
export const blueDark: string
export const blueInfo: string
export const blueLight: string
export const borderColorBlack: string
export const borderColorBlackBackground: string
export const borderColorBlackText: string
export const borderColorBlue: string
export const borderColorBlueDark: string
export const borderColorBlueInfo: string
export const borderColorBlueLight: string
export const borderColorDarkBlue: string
export const borderColorDarkGreen: string
export const borderColorDeepPurple: string
export const borderColorGreen: string
export const borderColorGreenBorder: string
export const borderColorGreenDark: string
export const borderColorGreenHover: string
export const borderColorGreenLight: string
export const borderColorGreenSuccess: string
export const borderColorGreyBackground: string
export const borderColorInherit: string
export const borderColorOrangeWarning: string
export const borderColorPink: string
export const borderColorPinkDark: string
export const borderColorPinkLight: string
export const borderColorPrimary: string
export const borderColorPrimaryDark: string
export const borderColorPrimaryLight: string
export const borderColorPurple: string
export const borderColorRedError: string
export const borderColorSecondary: string
export const borderColorSecondaryDark: string
export const borderColorSecondaryLight: string
export const borderColorTransparent: string
export const borderColorWhite: string
export const colorBlack: string
export const colorBlackBackground: string
export const colorBlackText: string
export const colorBlue: string
export const colorBlueDark: string
export const colorBlueInfo: string
export const colorBlueLight: string
export const colorDarkBlue: string
export const colorDarkGreen: string
export const colorDeepPurple: string
export const colorGreen: string
export const colorGreenBorder: string
export const colorGreenDark: string
export const colorGreenHover: string
export const colorGreenLight: string
export const colorGreenSuccess: string
export const colorGreyBackground: string
export const colorInherit: string
export const colorOrangeWarning: string
export const colorPink: string
export const colorPinkDark: string
export const colorPinkLight: string
export const colorPrimary: string
export const colorPrimaryDark: string
export const colorPrimaryLight: string
export const colorPurple: string
export const colorRedError: string
export const colorSecondary: string
export const colorSecondaryDark: string
export const colorSecondaryLight: string
export const colorTransparent: string
export const colorWhite: string
export const darkBlue: string
export const darkGreen: string
export const deepPurple: string
export const fillBlack: string
export const fillBlackBackground: string
export const fillBlackText: string
export const fillBlue: string
export const fillBlueDark: string
export const fillBlueInfo: string
export const fillBlueLight: string
export const fillDarkBlue: string
export const fillDarkGreen: string
export const fillDeepPurple: string
export const fillGreen: string
export const fillGreenBorder: string
export const fillGreenDark: string
export const fillGreenHover: string
export const fillGreenLight: string
export const fillGreenSuccess: string
export const fillGreyBackground: string
export const fillInherit: string
export const fillOrangeWarning: string
export const fillPink: string
export const fillPinkDark: string
export const fillPinkLight: string
export const fillPrimary: string
export const fillPrimaryDark: string
export const fillPrimaryLight: string
export const fillPurple: string
export const fillRedError: string
export const fillSecondary: string
export const fillSecondaryDark: string
export const fillSecondaryLight: string
export const fillTransparent: string
export const fillWhite: string
export const fontSizeBody1: string
export const fontSizeBody2: string
export const fontSizeBody3: string
export const fontSizeBody4: string
export const fontSizeButton: string
export const fontSizeCaption: string
export const fontSizeH1: string
export const fontSizeH2: string
export const fontSizeH3: string
export const fontSizeH4: string
export const fontSizeH5: string
export const fontSizeH6: string
export const fontSizeOverline: string
export const fontSizeSubtitle1: string
export const fontSizeSubtitle2: string
export const fontSizeTitle1: string
export const fontSizeTitle2: string
export const fontSizeTitle3: string
export const fontSizeTitle4: string
export const fontSizeTitle5: string
export const fontTheBadgeWeb: string
export const fontWeightBlack: string
export const fontWeightBold: string
export const fontWeightExtraBold: string
export const fontWeightExtraLarge: string
export const fontWeightLarge: string
export const fontWeightNormal: string
export const fontWeightThin: string
export const gradient0: string
export const gradient1: string
export const gradient2: string
export const gradient3: string
export const gradient4: string
export const gradient5: string
export const gradientBackground: string
export const gradientHeader: string
export const green: string
export const greenBorder: string
export const greenDark: string
export const greenHover: string
export const greenLight: string
export const greenSuccess: string
export const greyBackground: string
export const heightPc_0: string
export const heightPc_1: string
export const heightPc_10: string
export const heightPc_100: string
export const heightPc_11: string
export const heightPc_12: string
export const heightPc_13: string
export const heightPc_14: string
export const heightPc_15: string
export const heightPc_16: string
export const heightPc_17: string
export const heightPc_18: string
export const heightPc_19: string
export const heightPc_2: string
export const heightPc_20: string
export const heightPc_21: string
export const heightPc_22: string
export const heightPc_23: string
export const heightPc_24: string
export const heightPc_25: string
export const heightPc_26: string
export const heightPc_27: string
export const heightPc_28: string
export const heightPc_29: string
export const heightPc_3: string
export const heightPc_30: string
export const heightPc_31: string
export const heightPc_32: string
export const heightPc_33: string
export const heightPc_34: string
export const heightPc_35: string
export const heightPc_36: string
export const heightPc_37: string
export const heightPc_38: string
export const heightPc_39: string
export const heightPc_4: string
export const heightPc_40: string
export const heightPc_41: string
export const heightPc_42: string
export const heightPc_43: string
export const heightPc_44: string
export const heightPc_45: string
export const heightPc_46: string
export const heightPc_47: string
export const heightPc_48: string
export const heightPc_49: string
export const heightPc_5: string
export const heightPc_50: string
export const heightPc_51: string
export const heightPc_52: string
export const heightPc_53: string
export const heightPc_54: string
export const heightPc_55: string
export const heightPc_56: string
export const heightPc_57: string
export const heightPc_58: string
export const heightPc_59: string
export const heightPc_6: string
export const heightPc_60: string
export const heightPc_61: string
export const heightPc_62: string
export const heightPc_63: string
export const heightPc_64: string
export const heightPc_65: string
export const heightPc_66: string
export const heightPc_67: string
export const heightPc_68: string
export const heightPc_69: string
export const heightPc_7: string
export const heightPc_70: string
export const heightPc_71: string
export const heightPc_72: string
export const heightPc_73: string
export const heightPc_74: string
export const heightPc_75: string
export const heightPc_76: string
export const heightPc_77: string
export const heightPc_78: string
export const heightPc_79: string
export const heightPc_8: string
export const heightPc_80: string
export const heightPc_81: string
export const heightPc_82: string
export const heightPc_83: string
export const heightPc_84: string
export const heightPc_85: string
export const heightPc_86: string
export const heightPc_87: string
export const heightPc_88: string
export const heightPc_89: string
export const heightPc_9: string
export const heightPc_90: string
export const heightPc_91: string
export const heightPc_92: string
export const heightPc_93: string
export const heightPc_94: string
export const heightPc_95: string
export const heightPc_96: string
export const heightPc_97: string
export const heightPc_98: string
export const heightPc_99: string
export const l: string
export const lineHeightBody1: string
export const lineHeightBody2: string
export const lineHeightBody3: string
export const lineHeightBody4: string
export const lineHeightButton: string
export const lineHeightCaption: string
export const lineHeightH1: string
export const lineHeightH2: string
export const lineHeightH3: string
export const lineHeightH4: string
export const lineHeightH5: string
export const lineHeightH6: string
export const lineHeightOverline: string
export const lineHeightSubtitle1: string
export const lineHeightSubtitle2: string
export const lineHeightTitle1: string
export const lineHeightTitle2: string
export const lineHeightTitle3: string
export const lineHeightTitle4: string
export const lineHeightTitle5: string
export const m: string
export const orangeWarning: string
export const pink: string
export const pinkDark: string
export const pinkLight: string
export const primary: string
export const primaryDark: string
export const primaryLight: string
export const purple: string
export const redError: string
export const s: string
export const secondary: string
export const secondaryDark: string
export const secondaryLight: string
export const srOnly: string
export const svgFillBlack: string
export const svgFillBlackBackground: string
export const svgFillBlackText: string
export const svgFillBlue: string
export const svgFillBlueDark: string
export const svgFillBlueInfo: string
export const svgFillBlueLight: string
export const svgFillDarkBlue: string
export const svgFillDarkGreen: string
export const svgFillDeepPurple: string
export const svgFillGreen: string
export const svgFillGreenBorder: string
export const svgFillGreenDark: string
export const svgFillGreenHover: string
export const svgFillGreenLight: string
export const svgFillGreenSuccess: string
export const svgFillGreyBackground: string
export const svgFillInherit: string
export const svgFillOrangeWarning: string
export const svgFillPink: string
export const svgFillPinkDark: string
export const svgFillPinkLight: string
export const svgFillPrimary: string
export const svgFillPrimaryDark: string
export const svgFillPrimaryLight: string
export const svgFillPurple: string
export const svgFillRedError: string
export const svgFillSecondary: string
export const svgFillSecondaryDark: string
export const svgFillSecondaryLight: string
export const svgFillTransparent: string
export const svgFillWhite: string
export const textMaxLines_1: string
export const textMaxLines_10: string
export const textMaxLines_100: string
export const textMaxLines_11: string
export const textMaxLines_12: string
export const textMaxLines_13: string
export const textMaxLines_14: string
export const textMaxLines_15: string
export const textMaxLines_16: string
export const textMaxLines_17: string
export const textMaxLines_18: string
export const textMaxLines_19: string
export const textMaxLines_2: string
export const textMaxLines_20: string
export const textMaxLines_21: string
export const textMaxLines_22: string
export const textMaxLines_23: string
export const textMaxLines_24: string
export const textMaxLines_25: string
export const textMaxLines_26: string
export const textMaxLines_27: string
export const textMaxLines_28: string
export const textMaxLines_29: string
export const textMaxLines_3: string
export const textMaxLines_30: string
export const textMaxLines_31: string
export const textMaxLines_32: string
export const textMaxLines_33: string
export const textMaxLines_34: string
export const textMaxLines_35: string
export const textMaxLines_36: string
export const textMaxLines_37: string
export const textMaxLines_38: string
export const textMaxLines_39: string
export const textMaxLines_4: string
export const textMaxLines_40: string
export const textMaxLines_41: string
export const textMaxLines_42: string
export const textMaxLines_43: string
export const textMaxLines_44: string
export const textMaxLines_45: string
export const textMaxLines_46: string
export const textMaxLines_47: string
export const textMaxLines_48: string
export const textMaxLines_49: string
export const textMaxLines_5: string
export const textMaxLines_50: string
export const textMaxLines_51: string
export const textMaxLines_52: string
export const textMaxLines_53: string
export const textMaxLines_54: string
export const textMaxLines_55: string
export const textMaxLines_56: string
export const textMaxLines_57: string
export const textMaxLines_58: string
export const textMaxLines_59: string
export const textMaxLines_6: string
export const textMaxLines_60: string
export const textMaxLines_61: string
export const textMaxLines_62: string
export const textMaxLines_63: string
export const textMaxLines_64: string
export const textMaxLines_65: string
export const textMaxLines_66: string
export const textMaxLines_67: string
export const textMaxLines_68: string
export const textMaxLines_69: string
export const textMaxLines_7: string
export const textMaxLines_70: string
export const textMaxLines_71: string
export const textMaxLines_72: string
export const textMaxLines_73: string
export const textMaxLines_74: string
export const textMaxLines_75: string
export const textMaxLines_76: string
export const textMaxLines_77: string
export const textMaxLines_78: string
export const textMaxLines_79: string
export const textMaxLines_8: string
export const textMaxLines_80: string
export const textMaxLines_81: string
export const textMaxLines_82: string
export const textMaxLines_83: string
export const textMaxLines_84: string
export const textMaxLines_85: string
export const textMaxLines_86: string
export const textMaxLines_87: string
export const textMaxLines_88: string
export const textMaxLines_89: string
export const textMaxLines_9: string
export const textMaxLines_90: string
export const textMaxLines_91: string
export const textMaxLines_92: string
export const textMaxLines_93: string
export const textMaxLines_94: string
export const textMaxLines_95: string
export const textMaxLines_96: string
export const textMaxLines_97: string
export const textMaxLines_98: string
export const textMaxLines_99: string
export const textUnderline: string
export const textUnderlineWhite: string
export const transparent: string
export const white: string
export const widthPc_0: string
export const widthPc_1: string
export const widthPc_10: string
export const widthPc_100: string
export const widthPc_11: string
export const widthPc_12: string
export const widthPc_13: string
export const widthPc_14: string
export const widthPc_15: string
export const widthPc_16: string
export const widthPc_17: string
export const widthPc_18: string
export const widthPc_19: string
export const widthPc_2: string
export const widthPc_20: string
export const widthPc_21: string
export const widthPc_22: string
export const widthPc_23: string
export const widthPc_24: string
export const widthPc_25: string
export const widthPc_26: string
export const widthPc_27: string
export const widthPc_28: string
export const widthPc_29: string
export const widthPc_3: string
export const widthPc_30: string
export const widthPc_31: string
export const widthPc_32: string
export const widthPc_33: string
export const widthPc_34: string
export const widthPc_35: string
export const widthPc_36: string
export const widthPc_37: string
export const widthPc_38: string
export const widthPc_39: string
export const widthPc_4: string
export const widthPc_40: string
export const widthPc_41: string
export const widthPc_42: string
export const widthPc_43: string
export const widthPc_44: string
export const widthPc_45: string
export const widthPc_46: string
export const widthPc_47: string
export const widthPc_48: string
export const widthPc_49: string
export const widthPc_5: string
export const widthPc_50: string
export const widthPc_51: string
export const widthPc_52: string
export const widthPc_53: string
export const widthPc_54: string
export const widthPc_55: string
export const widthPc_56: string
export const widthPc_57: string
export const widthPc_58: string
export const widthPc_59: string
export const widthPc_6: string
export const widthPc_60: string
export const widthPc_61: string
export const widthPc_62: string
export const widthPc_63: string
export const widthPc_64: string
export const widthPc_65: string
export const widthPc_66: string
export const widthPc_67: string
export const widthPc_68: string
export const widthPc_69: string
export const widthPc_7: string
export const widthPc_70: string
export const widthPc_71: string
export const widthPc_72: string
export const widthPc_73: string
export const widthPc_74: string
export const widthPc_75: string
export const widthPc_76: string
export const widthPc_77: string
export const widthPc_78: string
export const widthPc_79: string
export const widthPc_8: string
export const widthPc_80: string
export const widthPc_81: string
export const widthPc_82: string
export const widthPc_83: string
export const widthPc_84: string
export const widthPc_85: string
export const widthPc_86: string
export const widthPc_87: string
export const widthPc_88: string
export const widthPc_89: string
export const widthPc_9: string
export const widthPc_90: string
export const widthPc_91: string
export const widthPc_92: string
export const widthPc_93: string
export const widthPc_94: string
export const widthPc_95: string
export const widthPc_96: string
export const widthPc_97: string
export const widthPc_98: string
export const widthPc_99: string
export const xl: string
export const xxl: string
