export const backgroundColorBlack: string
export const backgroundColorBlackBackground: string
export const backgroundColorBlackBackgroundShadow: string
export const backgroundColorBlackText: string
export const backgroundColorBlue: string
export const backgroundColorBlueDark: string
export const backgroundColorBlueInfo: string
export const backgroundColorBlueLight: string
export const backgroundColorDarkBlue: string
export const backgroundColorDarkGreen: string
export const backgroundColorDeepPurple: string
export const backgroundColorGreen: string
export const backgroundColorGreenBorder: string
export const backgroundColorGreenDark: string
export const backgroundColorGreenHover: string
export const backgroundColorGreenLight: string
export const backgroundColorGreenLogo: string
export const backgroundColorGreenSuccess: string
export const backgroundColorGreyBackground: string
export const backgroundColorGreyStroke: string
export const backgroundColorInherit: string
export const backgroundColorOrangeWarning: string
export const backgroundColorPink: string
export const backgroundColorPinkDark: string
export const backgroundColorPinkLight: string
export const backgroundColorPrimary: string
export const backgroundColorPrimaryDark: string
export const backgroundColorPrimaryLight: string
export const backgroundColorPurple: string
export const backgroundColorRedError: string
export const backgroundColorSecondary: string
export const backgroundColorSecondaryDark: string
export const backgroundColorSecondaryLight: string
export const backgroundColorTransparent: string
export const backgroundColorWhite: string
export const backgroundGradient0: string
export const backgroundGradient1: string
export const backgroundGradient2: string
export const backgroundGradient3: string
export const backgroundGradient4: string
export const backgroundGradient5: string
export const backgroundGradientBackgroundDark: string
export const backgroundGradientBackgroundLight: string
export const backgroundGradientHeader: string
export const backgroundInherit: string
export const black: string
export const blackBackground: string
export const blackBackgroundShadow: string
export const blackText: string
export const blue: string
export const blueDark: string
export const blueInfo: string
export const blueLight: string
export const borderColorBlack: string
export const borderColorBlackBackground: string
export const borderColorBlackBackgroundShadow: string
export const borderColorBlackText: string
export const borderColorBlue: string
export const borderColorBlueDark: string
export const borderColorBlueInfo: string
export const borderColorBlueLight: string
export const borderColorDarkBlue: string
export const borderColorDarkGreen: string
export const borderColorDeepPurple: string
export const borderColorGreen: string
export const borderColorGreenBorder: string
export const borderColorGreenDark: string
export const borderColorGreenHover: string
export const borderColorGreenLight: string
export const borderColorGreenLogo: string
export const borderColorGreenSuccess: string
export const borderColorGreyBackground: string
export const borderColorGreyStroke: string
export const borderColorInherit: string
export const borderColorOrangeWarning: string
export const borderColorPink: string
export const borderColorPinkDark: string
export const borderColorPinkLight: string
export const borderColorPrimary: string
export const borderColorPrimaryDark: string
export const borderColorPrimaryLight: string
export const borderColorPurple: string
export const borderColorRedError: string
export const borderColorSecondary: string
export const borderColorSecondaryDark: string
export const borderColorSecondaryLight: string
export const borderColorTransparent: string
export const borderColorWhite: string
export const colorBlack: string
export const colorBlackBackground: string
export const colorBlackBackgroundShadow: string
export const colorBlackText: string
export const colorBlue: string
export const colorBlueDark: string
export const colorBlueInfo: string
export const colorBlueLight: string
export const colorDarkBlue: string
export const colorDarkGreen: string
export const colorDeepPurple: string
export const colorGreen: string
export const colorGreenBorder: string
export const colorGreenDark: string
export const colorGreenHover: string
export const colorGreenLight: string
export const colorGreenLogo: string
export const colorGreenSuccess: string
export const colorGreyBackground: string
export const colorGreyStroke: string
export const colorInherit: string
export const colorOrangeWarning: string
export const colorPink: string
export const colorPinkDark: string
export const colorPinkLight: string
export const colorPrimary: string
export const colorPrimaryDark: string
export const colorPrimaryLight: string
export const colorPurple: string
export const colorRedError: string
export const colorSecondary: string
export const colorSecondaryDark: string
export const colorSecondaryLight: string
export const colorTransparent: string
export const colorWhite: string
export const darkBlue: string
export const darkGreen: string
export const deepPurple: string
export const fillBlack: string
export const fillBlackBackground: string
export const fillBlackBackgroundShadow: string
export const fillBlackText: string
export const fillBlue: string
export const fillBlueDark: string
export const fillBlueInfo: string
export const fillBlueLight: string
export const fillDarkBlue: string
export const fillDarkGreen: string
export const fillDeepPurple: string
export const fillGreen: string
export const fillGreenBorder: string
export const fillGreenDark: string
export const fillGreenHover: string
export const fillGreenLight: string
export const fillGreenLogo: string
export const fillGreenSuccess: string
export const fillGreyBackground: string
export const fillGreyStroke: string
export const fillInherit: string
export const fillOrangeWarning: string
export const fillPink: string
export const fillPinkDark: string
export const fillPinkLight: string
export const fillPrimary: string
export const fillPrimaryDark: string
export const fillPrimaryLight: string
export const fillPurple: string
export const fillRedError: string
export const fillSecondary: string
export const fillSecondaryDark: string
export const fillSecondaryLight: string
export const fillTransparent: string
export const fillWhite: string
export const fontSizeBody1: string
export const fontSizeBody2: string
export const fontSizeBody3: string
export const fontSizeBody4: string
export const fontSizeButton: string
export const fontSizeCaption: string
export const fontSizeDAppBody1: string
export const fontSizeDAppBody3: string
export const fontSizeDAppBody4: string
export const fontSizeDAppButton: string
export const fontSizeDAppDayshours: string
export const fontSizeDAppHeadline1: string
export const fontSizeDAppHeadline2: string
export const fontSizeDAppNumber: string
export const fontSizeDAppTitle1: string
export const fontSizeDAppTitle2: string
export const fontSizeDAppTitle3: string
export const fontSizeDAppTitle4: string
export const fontSizeDAppTitle5: string
export const fontSizeH1: string
export const fontSizeH2: string
export const fontSizeH3: string
export const fontSizeH4: string
export const fontSizeH5: string
export const fontSizeH6: string
export const fontSizeOverline: string
export const fontSizeSubtitle1: string
export const fontSizeSubtitle2: string
export const fontSizeTitle1: string
export const fontSizeTitle2: string
export const fontSizeTitle3: string
export const fontSizeTitle4: string
export const fontSizeTitle5: string
export const fontTheBadgeWeb: string
export const fontWeightBlack: string
export const fontWeightBold: string
export const fontWeightExtraBold: string
export const fontWeightExtraLarge: string
export const fontWeightLarge: string
export const fontWeightNormal: string
export const fontWeightThin: string
export const gradient0: string
export const gradient1: string
export const gradient2: string
export const gradient3: string
export const gradient4: string
export const gradient5: string
export const gradientBackgroundDark: string
export const gradientBackgroundLight: string
export const gradientHeader: string
export const green: string
export const greenBorder: string
export const greenDark: string
export const greenHover: string
export const greenLight: string
export const greenLogo: string
export const greenSuccess: string
export const greyBackground: string
export const greyStroke: string
export const heightPc0: string
export const heightPc1: string
export const heightPc10: string
export const heightPc100: string
export const heightPc11: string
export const heightPc12: string
export const heightPc13: string
export const heightPc14: string
export const heightPc15: string
export const heightPc16: string
export const heightPc17: string
export const heightPc18: string
export const heightPc19: string
export const heightPc2: string
export const heightPc20: string
export const heightPc21: string
export const heightPc22: string
export const heightPc23: string
export const heightPc24: string
export const heightPc25: string
export const heightPc26: string
export const heightPc27: string
export const heightPc28: string
export const heightPc29: string
export const heightPc3: string
export const heightPc30: string
export const heightPc31: string
export const heightPc32: string
export const heightPc33: string
export const heightPc34: string
export const heightPc35: string
export const heightPc36: string
export const heightPc37: string
export const heightPc38: string
export const heightPc39: string
export const heightPc4: string
export const heightPc40: string
export const heightPc41: string
export const heightPc42: string
export const heightPc43: string
export const heightPc44: string
export const heightPc45: string
export const heightPc46: string
export const heightPc47: string
export const heightPc48: string
export const heightPc49: string
export const heightPc5: string
export const heightPc50: string
export const heightPc51: string
export const heightPc52: string
export const heightPc53: string
export const heightPc54: string
export const heightPc55: string
export const heightPc56: string
export const heightPc57: string
export const heightPc58: string
export const heightPc59: string
export const heightPc6: string
export const heightPc60: string
export const heightPc61: string
export const heightPc62: string
export const heightPc63: string
export const heightPc64: string
export const heightPc65: string
export const heightPc66: string
export const heightPc67: string
export const heightPc68: string
export const heightPc69: string
export const heightPc7: string
export const heightPc70: string
export const heightPc71: string
export const heightPc72: string
export const heightPc73: string
export const heightPc74: string
export const heightPc75: string
export const heightPc76: string
export const heightPc77: string
export const heightPc78: string
export const heightPc79: string
export const heightPc8: string
export const heightPc80: string
export const heightPc81: string
export const heightPc82: string
export const heightPc83: string
export const heightPc84: string
export const heightPc85: string
export const heightPc86: string
export const heightPc87: string
export const heightPc88: string
export const heightPc89: string
export const heightPc9: string
export const heightPc90: string
export const heightPc91: string
export const heightPc92: string
export const heightPc93: string
export const heightPc94: string
export const heightPc95: string
export const heightPc96: string
export const heightPc97: string
export const heightPc98: string
export const heightPc99: string
export const l: string
export const lineHeightBody1: string
export const lineHeightBody2: string
export const lineHeightBody3: string
export const lineHeightBody4: string
export const lineHeightButton: string
export const lineHeightCaption: string
export const lineHeightDAppBody1: string
export const lineHeightDAppBody3: string
export const lineHeightDAppBody4: string
export const lineHeightDAppButton: string
export const lineHeightDAppDayshours: string
export const lineHeightDAppHeadline1: string
export const lineHeightDAppHeadline2: string
export const lineHeightDAppNumber: string
export const lineHeightDAppTitle1: string
export const lineHeightDAppTitle2: string
export const lineHeightDAppTitle3: string
export const lineHeightDAppTitle4: string
export const lineHeightDAppTitle5: string
export const lineHeightH1: string
export const lineHeightH2: string
export const lineHeightH3: string
export const lineHeightH4: string
export const lineHeightH5: string
export const lineHeightH6: string
export const lineHeightOverline: string
export const lineHeightSubtitle1: string
export const lineHeightSubtitle2: string
export const lineHeightTitle1: string
export const lineHeightTitle2: string
export const lineHeightTitle3: string
export const lineHeightTitle4: string
export const lineHeightTitle5: string
export const m: string
export const orangeWarning: string
export const pink: string
export const pinkDark: string
export const pinkLight: string
export const primary: string
export const primaryDark: string
export const primaryLight: string
export const purple: string
export const redError: string
export const s: string
export const secondary: string
export const secondaryDark: string
export const secondaryLight: string
export const srOnly: string
export const svgFillBlack: string
export const svgFillBlackBackground: string
export const svgFillBlackBackgroundShadow: string
export const svgFillBlackText: string
export const svgFillBlue: string
export const svgFillBlueDark: string
export const svgFillBlueInfo: string
export const svgFillBlueLight: string
export const svgFillDarkBlue: string
export const svgFillDarkGreen: string
export const svgFillDeepPurple: string
export const svgFillGreen: string
export const svgFillGreenBorder: string
export const svgFillGreenDark: string
export const svgFillGreenHover: string
export const svgFillGreenLight: string
export const svgFillGreenLogo: string
export const svgFillGreenSuccess: string
export const svgFillGreyBackground: string
export const svgFillGreyStroke: string
export const svgFillInherit: string
export const svgFillOrangeWarning: string
export const svgFillPink: string
export const svgFillPinkDark: string
export const svgFillPinkLight: string
export const svgFillPrimary: string
export const svgFillPrimaryDark: string
export const svgFillPrimaryLight: string
export const svgFillPurple: string
export const svgFillRedError: string
export const svgFillSecondary: string
export const svgFillSecondaryDark: string
export const svgFillSecondaryLight: string
export const svgFillTransparent: string
export const svgFillWhite: string
export const textMaxLines1: string
export const textMaxLines10: string
export const textMaxLines100: string
export const textMaxLines11: string
export const textMaxLines12: string
export const textMaxLines13: string
export const textMaxLines14: string
export const textMaxLines15: string
export const textMaxLines16: string
export const textMaxLines17: string
export const textMaxLines18: string
export const textMaxLines19: string
export const textMaxLines2: string
export const textMaxLines20: string
export const textMaxLines21: string
export const textMaxLines22: string
export const textMaxLines23: string
export const textMaxLines24: string
export const textMaxLines25: string
export const textMaxLines26: string
export const textMaxLines27: string
export const textMaxLines28: string
export const textMaxLines29: string
export const textMaxLines3: string
export const textMaxLines30: string
export const textMaxLines31: string
export const textMaxLines32: string
export const textMaxLines33: string
export const textMaxLines34: string
export const textMaxLines35: string
export const textMaxLines36: string
export const textMaxLines37: string
export const textMaxLines38: string
export const textMaxLines39: string
export const textMaxLines4: string
export const textMaxLines40: string
export const textMaxLines41: string
export const textMaxLines42: string
export const textMaxLines43: string
export const textMaxLines44: string
export const textMaxLines45: string
export const textMaxLines46: string
export const textMaxLines47: string
export const textMaxLines48: string
export const textMaxLines49: string
export const textMaxLines5: string
export const textMaxLines50: string
export const textMaxLines51: string
export const textMaxLines52: string
export const textMaxLines53: string
export const textMaxLines54: string
export const textMaxLines55: string
export const textMaxLines56: string
export const textMaxLines57: string
export const textMaxLines58: string
export const textMaxLines59: string
export const textMaxLines6: string
export const textMaxLines60: string
export const textMaxLines61: string
export const textMaxLines62: string
export const textMaxLines63: string
export const textMaxLines64: string
export const textMaxLines65: string
export const textMaxLines66: string
export const textMaxLines67: string
export const textMaxLines68: string
export const textMaxLines69: string
export const textMaxLines7: string
export const textMaxLines70: string
export const textMaxLines71: string
export const textMaxLines72: string
export const textMaxLines73: string
export const textMaxLines74: string
export const textMaxLines75: string
export const textMaxLines76: string
export const textMaxLines77: string
export const textMaxLines78: string
export const textMaxLines79: string
export const textMaxLines8: string
export const textMaxLines80: string
export const textMaxLines81: string
export const textMaxLines82: string
export const textMaxLines83: string
export const textMaxLines84: string
export const textMaxLines85: string
export const textMaxLines86: string
export const textMaxLines87: string
export const textMaxLines88: string
export const textMaxLines89: string
export const textMaxLines9: string
export const textMaxLines90: string
export const textMaxLines91: string
export const textMaxLines92: string
export const textMaxLines93: string
export const textMaxLines94: string
export const textMaxLines95: string
export const textMaxLines96: string
export const textMaxLines97: string
export const textMaxLines98: string
export const textMaxLines99: string
export const textUnderline: string
export const textUnderlineWhite: string
export const transparent: string
export const white: string
export const widthPc0: string
export const widthPc1: string
export const widthPc10: string
export const widthPc100: string
export const widthPc11: string
export const widthPc12: string
export const widthPc13: string
export const widthPc14: string
export const widthPc15: string
export const widthPc16: string
export const widthPc17: string
export const widthPc18: string
export const widthPc19: string
export const widthPc2: string
export const widthPc20: string
export const widthPc21: string
export const widthPc22: string
export const widthPc23: string
export const widthPc24: string
export const widthPc25: string
export const widthPc26: string
export const widthPc27: string
export const widthPc28: string
export const widthPc29: string
export const widthPc3: string
export const widthPc30: string
export const widthPc31: string
export const widthPc32: string
export const widthPc33: string
export const widthPc34: string
export const widthPc35: string
export const widthPc36: string
export const widthPc37: string
export const widthPc38: string
export const widthPc39: string
export const widthPc4: string
export const widthPc40: string
export const widthPc41: string
export const widthPc42: string
export const widthPc43: string
export const widthPc44: string
export const widthPc45: string
export const widthPc46: string
export const widthPc47: string
export const widthPc48: string
export const widthPc49: string
export const widthPc5: string
export const widthPc50: string
export const widthPc51: string
export const widthPc52: string
export const widthPc53: string
export const widthPc54: string
export const widthPc55: string
export const widthPc56: string
export const widthPc57: string
export const widthPc58: string
export const widthPc59: string
export const widthPc6: string
export const widthPc60: string
export const widthPc61: string
export const widthPc62: string
export const widthPc63: string
export const widthPc64: string
export const widthPc65: string
export const widthPc66: string
export const widthPc67: string
export const widthPc68: string
export const widthPc69: string
export const widthPc7: string
export const widthPc70: string
export const widthPc71: string
export const widthPc72: string
export const widthPc73: string
export const widthPc74: string
export const widthPc75: string
export const widthPc76: string
export const widthPc77: string
export const widthPc78: string
export const widthPc79: string
export const widthPc8: string
export const widthPc80: string
export const widthPc81: string
export const widthPc82: string
export const widthPc83: string
export const widthPc84: string
export const widthPc85: string
export const widthPc86: string
export const widthPc87: string
export const widthPc88: string
export const widthPc89: string
export const widthPc9: string
export const widthPc90: string
export const widthPc91: string
export const widthPc92: string
export const widthPc93: string
export const widthPc94: string
export const widthPc95: string
export const widthPc96: string
export const widthPc97: string
export const widthPc98: string
export const widthPc99: string
export const xl: string
export const xxl: string
