export const backgroundColorBlack: string
export const backgroundColorBlackBackground: string
export const backgroundColorBlackText: string
export const backgroundColorBlue: string
export const backgroundColorBlueDark: string
export const backgroundColorBlueInfo: string
export const backgroundColorBlueLight: string
export const backgroundColorDarkBlue: string
export const backgroundColorDarkGreen: string
export const backgroundColorDeepPurple: string
export const backgroundColorGreen: string
export const backgroundColorGreenBorder: string
export const backgroundColorGreenDark: string
export const backgroundColorGreenHover: string
export const backgroundColorGreenLight: string
export const backgroundColorGreenSuccess: string
export const backgroundColorGreyBackground: string
export const backgroundColorInherit: string
export const backgroundColorOrangeWarning: string
export const backgroundColorPink: string
export const backgroundColorPinkDark: string
export const backgroundColorPinkLight: string
export const backgroundColorPrimary: string
export const backgroundColorPrimaryDark: string
export const backgroundColorPrimaryLight: string
export const backgroundColorPurple: string
export const backgroundColorRedError: string
export const backgroundColorSecondary: string
export const backgroundColorSecondaryDark: string
export const backgroundColorSecondaryLight: string
export const backgroundColorTransparent: string
export const backgroundColorWhite: string
export const black: string
export const blackBackground: string
export const blackText: string
export const blue: string
export const blueDark: string
export const blueInfo: string
export const blueLight: string
export const borderColorBlack: string
export const borderColorBlackBackground: string
export const borderColorBlackText: string
export const borderColorBlue: string
export const borderColorBlueDark: string
export const borderColorBlueInfo: string
export const borderColorBlueLight: string
export const borderColorDarkBlue: string
export const borderColorDarkGreen: string
export const borderColorDeepPurple: string
export const borderColorGreen: string
export const borderColorGreenBorder: string
export const borderColorGreenDark: string
export const borderColorGreenHover: string
export const borderColorGreenLight: string
export const borderColorGreenSuccess: string
export const borderColorGreyBackground: string
export const borderColorInherit: string
export const borderColorOrangeWarning: string
export const borderColorPink: string
export const borderColorPinkDark: string
export const borderColorPinkLight: string
export const borderColorPrimary: string
export const borderColorPrimaryDark: string
export const borderColorPrimaryLight: string
export const borderColorPurple: string
export const borderColorRedError: string
export const borderColorSecondary: string
export const borderColorSecondaryDark: string
export const borderColorSecondaryLight: string
export const borderColorTransparent: string
export const borderColorWhite: string
export const colorBlack: string
export const colorBlackBackground: string
export const colorBlackText: string
export const colorBlue: string
export const colorBlueDark: string
export const colorBlueInfo: string
export const colorBlueLight: string
export const colorDarkBlue: string
export const colorDarkGreen: string
export const colorDeepPurple: string
export const colorGreen: string
export const colorGreenBorder: string
export const colorGreenDark: string
export const colorGreenHover: string
export const colorGreenLight: string
export const colorGreenSuccess: string
export const colorGreyBackground: string
export const colorInherit: string
export const colorOrangeWarning: string
export const colorPink: string
export const colorPinkDark: string
export const colorPinkLight: string
export const colorPrimary: string
export const colorPrimaryDark: string
export const colorPrimaryLight: string
export const colorPurple: string
export const colorRedError: string
export const colorSecondary: string
export const colorSecondaryDark: string
export const colorSecondaryLight: string
export const colorTransparent: string
export const colorWhite: string
export const darkBlue: string
export const darkGreen: string
export const deepPurple: string
export const fillBlack: string
export const fillBlackBackground: string
export const fillBlackText: string
export const fillBlue: string
export const fillBlueDark: string
export const fillBlueInfo: string
export const fillBlueLight: string
export const fillDarkBlue: string
export const fillDarkGreen: string
export const fillDeepPurple: string
export const fillGreen: string
export const fillGreenBorder: string
export const fillGreenDark: string
export const fillGreenHover: string
export const fillGreenLight: string
export const fillGreenSuccess: string
export const fillGreyBackground: string
export const fillInherit: string
export const fillOrangeWarning: string
export const fillPink: string
export const fillPinkDark: string
export const fillPinkLight: string
export const fillPrimary: string
export const fillPrimaryDark: string
export const fillPrimaryLight: string
export const fillPurple: string
export const fillRedError: string
export const fillSecondary: string
export const fillSecondaryDark: string
export const fillSecondaryLight: string
export const fillTransparent: string
export const fillWhite: string
export const green: string
export const greenBorder: string
export const greenDark: string
export const greenHover: string
export const greenLight: string
export const greenSuccess: string
export const greyBackground: string
export const orangeWarning: string
export const pink: string
export const pinkDark: string
export const pinkLight: string
export const primary: string
export const primaryDark: string
export const primaryLight: string
export const purple: string
export const redError: string
export const secondary: string
export const secondaryDark: string
export const secondaryLight: string
export const svgFillBlack: string
export const svgFillBlackBackground: string
export const svgFillBlackText: string
export const svgFillBlue: string
export const svgFillBlueDark: string
export const svgFillBlueInfo: string
export const svgFillBlueLight: string
export const svgFillDarkBlue: string
export const svgFillDarkGreen: string
export const svgFillDeepPurple: string
export const svgFillGreen: string
export const svgFillGreenBorder: string
export const svgFillGreenDark: string
export const svgFillGreenHover: string
export const svgFillGreenLight: string
export const svgFillGreenSuccess: string
export const svgFillGreyBackground: string
export const svgFillInherit: string
export const svgFillOrangeWarning: string
export const svgFillPink: string
export const svgFillPinkDark: string
export const svgFillPinkLight: string
export const svgFillPrimary: string
export const svgFillPrimaryDark: string
export const svgFillPrimaryLight: string
export const svgFillPurple: string
export const svgFillRedError: string
export const svgFillSecondary: string
export const svgFillSecondaryDark: string
export const svgFillSecondaryLight: string
export const svgFillTransparent: string
export const svgFillWhite: string
export const transparent: string
export const white: string
