export const textMaxLines1: string
export const textMaxLines10: string
export const textMaxLines100: string
export const textMaxLines11: string
export const textMaxLines12: string
export const textMaxLines13: string
export const textMaxLines14: string
export const textMaxLines15: string
export const textMaxLines16: string
export const textMaxLines17: string
export const textMaxLines18: string
export const textMaxLines19: string
export const textMaxLines2: string
export const textMaxLines20: string
export const textMaxLines21: string
export const textMaxLines22: string
export const textMaxLines23: string
export const textMaxLines24: string
export const textMaxLines25: string
export const textMaxLines26: string
export const textMaxLines27: string
export const textMaxLines28: string
export const textMaxLines29: string
export const textMaxLines3: string
export const textMaxLines30: string
export const textMaxLines31: string
export const textMaxLines32: string
export const textMaxLines33: string
export const textMaxLines34: string
export const textMaxLines35: string
export const textMaxLines36: string
export const textMaxLines37: string
export const textMaxLines38: string
export const textMaxLines39: string
export const textMaxLines4: string
export const textMaxLines40: string
export const textMaxLines41: string
export const textMaxLines42: string
export const textMaxLines43: string
export const textMaxLines44: string
export const textMaxLines45: string
export const textMaxLines46: string
export const textMaxLines47: string
export const textMaxLines48: string
export const textMaxLines49: string
export const textMaxLines5: string
export const textMaxLines50: string
export const textMaxLines51: string
export const textMaxLines52: string
export const textMaxLines53: string
export const textMaxLines54: string
export const textMaxLines55: string
export const textMaxLines56: string
export const textMaxLines57: string
export const textMaxLines58: string
export const textMaxLines59: string
export const textMaxLines6: string
export const textMaxLines60: string
export const textMaxLines61: string
export const textMaxLines62: string
export const textMaxLines63: string
export const textMaxLines64: string
export const textMaxLines65: string
export const textMaxLines66: string
export const textMaxLines67: string
export const textMaxLines68: string
export const textMaxLines69: string
export const textMaxLines7: string
export const textMaxLines70: string
export const textMaxLines71: string
export const textMaxLines72: string
export const textMaxLines73: string
export const textMaxLines74: string
export const textMaxLines75: string
export const textMaxLines76: string
export const textMaxLines77: string
export const textMaxLines78: string
export const textMaxLines79: string
export const textMaxLines8: string
export const textMaxLines80: string
export const textMaxLines81: string
export const textMaxLines82: string
export const textMaxLines83: string
export const textMaxLines84: string
export const textMaxLines85: string
export const textMaxLines86: string
export const textMaxLines87: string
export const textMaxLines88: string
export const textMaxLines89: string
export const textMaxLines9: string
export const textMaxLines90: string
export const textMaxLines91: string
export const textMaxLines92: string
export const textMaxLines93: string
export const textMaxLines94: string
export const textMaxLines95: string
export const textMaxLines96: string
export const textMaxLines97: string
export const textMaxLines98: string
export const textMaxLines99: string
